### ISSUE TITLE
Fetch a bunch of divs with pyppeteer #1 [$60 awarded]

### ISSUE THREAD

**Issue by fropl** [mercatos/Products#1]
Update https://gitlab.com/artemciy/idealo/-/blob/master/idealo.py to fetch and log Produktdetails and Preisvergleich from https://www.idealo.de/preisvergleich/OffersOfProduct/6296589_-eq-9-plus-siemens.html

Acceptance test: The program should log the shops (Zum Shop, ..), prices (1.066,03, ..) and details (Produkttyp: Kaffeevollautomat, Serie:
Siemens EQ.9 plus..)  obtrained with Pyppeteer from the page.

$30 - $60 bounty,
[![bounty](https://api.bountysource.com/badge/issue?issue_id=109217720)](https://app.bountysource.com/issues/109217720-fetch-a-bunch-of-divs-with-pyppeteer-1)

**Comment by fropl** [comment]
I marked all the zones that we need to get. If the information consists of text and a link, then we need to get them.

https://www.idealo.de/preisvergleich/OffersOfProduct/200268547_-eq-9-plus-connect-s500-ti9558x1de-siemens.html

![Image](https://user-images.githubusercontent.com/76975539/172828162-3a84141c-429e-4a64-9db6-dd17faf3249f.png)

**Comment by KN4CK3R** [comment]
I created a MR in Gitlab: https://gitlab.com/artemciy/idealo/-/merge_requests/2

**Comment by ArtemGr** [comment]
Awesome, thanks!
